/**
 * Tests pour buildManifestFromTree — la fonction qui genere un manifest
 * depuis l'arborescence d'un repo GitHub.
 *
 * Ne teste pas listRepoTree (necessite Octokit mocke). buildManifestFromTree
 * est exposee separement pour ces tests purs sur structure.
 */
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-jwt-secret-for-testing-only-32chars!!'

const { buildManifestFromTree, humanizeDirPath } = require('../../../server/services/lumenAutoManifest')
const { manifestSchema } = require('../../../server/services/lumenManifest')

/** Helper : valide qu'un manifest passe le schema Zod directement */
function validateAgainstSchema(manifest) {
  const parsed = manifestSchema.safeParse(manifest)
  if (!parsed.success) {
    const first = parsed.error.issues[0]
    throw new Error(`Schema invalide : ${first.path.join('.')} — ${first.message}`)
  }
  return parsed.data
}

describe('buildManifestFromTree', () => {
  it('arbre vide → chapitre placeholder, pas de crash', () => {
    const m = buildManifestFromTree([], { projectName: 'empty-repo' })
    expect(m.project).toBe('empty-repo')
    expect(m.chapters).toHaveLength(1)
    expect(m.chapters[0].title).toBe('Aucun chapitre')
    expect(m.autoGenerated).toBe(true)
    validateAgainstSchema(m)
  })

  it('README.md racine → premier chapitre "Accueil"', () => {
    const m = buildManifestFromTree(
      [{ path: 'README.md' }, { path: 'cours/01-intro.md' }],
      { projectName: 'test' },
    )
    expect(m.chapters[0]).toMatchObject({
      title: 'Accueil',
      path: 'README.md',
      section: 'Presentation',
      kind: 'markdown',
    })
    expect(m.chapters[1].title.toLowerCase()).toContain('intro')
    validateAgainstSchema(m)
  })

  it('profondeur (guides/php/1-intro.md) → section humanisee', () => {
    const m = buildManifestFromTree(
      [{ path: 'guides/php/1-intro.md' }, { path: 'guides/php/2-poo.md' }],
      { projectName: 'test' },
    )
    const sections = new Set(m.chapters.map((c) => c.section))
    expect(sections).toContain('Guides · Php')
    validateAgainstSchema(m)
  })

  it('ignored dirs (node_modules, .github, venv) sont exclus', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'node_modules/foo/bar.md' },
        { path: '.github/PULL_REQUEST_TEMPLATE.md' },
        { path: 'venv/lib/site.md' },
        { path: 'cours/01.md' },
      ],
      { projectName: 'test' },
    )
    const paths = m.chapters.map((c) => c.path)
    expect(paths).toContain('README.md')
    expect(paths).toContain('cours/01.md')
    expect(paths.find((p) => p.includes('node_modules'))).toBeUndefined()
    expect(paths.find((p) => p.includes('.github'))).toBeUndefined()
    expect(paths.find((p) => p.includes('venv'))).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('archives et images non-chapitre → resources (pdf est devenu chapitre en v2.64)', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'archive.zip' },
        { path: 'images/logo.png' },
      ],
      { projectName: 'test' },
    )
    expect(m.resources).toBeDefined()
    const resourcePaths = m.resources.map((r) => r.path)
    expect(resourcePaths).toContain('archive.zip')
    expect(resourcePaths).toContain('images/logo.png')
    validateAgainstSchema(m)
  })

  it('truncated: true est propage dans le manifest', () => {
    const m = buildManifestFromTree(
      [{ path: 'README.md' }, { path: 'cours/01.md' }],
      { projectName: 'test', truncated: true },
    )
    expect(m.truncated).toBe(true)
    validateAgainstSchema(m)
  })

  it('truncated absent par defaut quand option non passee', () => {
    const m = buildManifestFromTree([{ path: 'README.md' }], { projectName: 'test' })
    expect(m.truncated).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('sorting : prefixe numerique avant alphabetique', () => {
    const m = buildManifestFromTree(
      [
        { path: 'cours/zebra.md' },
        { path: 'cours/02-second.md' },
        { path: 'cours/10-tenth.md' },
        { path: 'cours/01-first.md' },
        { path: 'cours/abracadabra.md' },
      ],
      { projectName: 'test' },
    )
    // Les chapitres sous cours/ sont ordonnes par prefixe numerique puis alpha
    const cours = m.chapters.filter((c) => c.path.startsWith('cours/'))
    expect(cours[0].path).toBe('cours/01-first.md')
    expect(cours[1].path).toBe('cours/02-second.md')
    expect(cours[2].path).toBe('cours/10-tenth.md')
    // abracadabra < zebra alpha
    expect(cours[3].path).toBe('cours/abracadabra.md')
    expect(cours[4].path).toBe('cours/zebra.md')
    validateAgainstSchema(m)
  })

  it('aucun .md → chapitre placeholder, manifest valide quand meme', () => {
    const m = buildManifestFromTree(
      [{ path: 'data.json' }, { path: 'image.png' }],
      { projectName: 'binary-only' },
    )
    expect(m.chapters).toHaveLength(1)
    expect(m.chapters[0].path).toBe('README.md')
    expect(m.chapters[0].title).toBe('Aucun chapitre')
    validateAgainstSchema(m)
  })
})

// ── PDF / TeX support v2.64 ─────────────────────────────────────────────

describe('buildManifestFromTree : PDF et TeX (v2.64)', () => {
  it('PDF orphelin -> chapitre kind=pdf', () => {
    const m = buildManifestFromTree(
      [{ path: 'guide.pdf' }],
      { projectName: 'test' },
    )
    const ch = m.chapters.find((c) => c.path === 'guide.pdf')
    expect(ch).toBeDefined()
    expect(ch.kind).toBe('pdf')
    expect(ch.companionPdf).toBeUndefined()
    expect(ch.companionTex).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('TeX orphelin -> chapitre kind=tex', () => {
    const m = buildManifestFromTree(
      [{ path: 'qcm.tex' }],
      { projectName: 'test' },
    )
    const ch = m.chapters.find((c) => c.path === 'qcm.tex')
    expect(ch).toBeDefined()
    expect(ch.kind).toBe('tex')
    validateAgainstSchema(m)
  })

  it('paire .md + .pdf meme basename -> 1 chapitre kind=markdown avec companionPdf', () => {
    const m = buildManifestFromTree(
      [{ path: 'guides/scrum.md' }, { path: 'guides/scrum.pdf' }],
      { projectName: 'test' },
    )
    // Un seul chapitre emis (priorite md > pdf)
    expect(m.chapters.filter((c) => c.path.includes('scrum'))).toHaveLength(1)
    const ch = m.chapters.find((c) => c.path === 'guides/scrum.md')
    expect(ch).toBeDefined()
    expect(ch.kind).toBe('markdown')
    expect(ch.companionPdf).toBe('guides/scrum.pdf')
    expect(ch.companionTex).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('paire .tex + .pdf meme basename -> 1 chapitre kind=pdf avec companionTex', () => {
    const m = buildManifestFromTree(
      [{ path: 'sujets/qcm-equadiff.tex' }, { path: 'sujets/qcm-equadiff.pdf' }],
      { projectName: 'maths' },
    )
    expect(m.chapters.filter((c) => c.path.includes('qcm-equadiff'))).toHaveLength(1)
    const ch = m.chapters.find((c) => c.path === 'sujets/qcm-equadiff.pdf')
    expect(ch).toBeDefined()
    expect(ch.kind).toBe('pdf')
    expect(ch.companionTex).toBe('sujets/qcm-equadiff.tex')
    validateAgainstSchema(m)
  })

  it('triple .md + .pdf + .tex -> 1 chapitre md + pdf compagnon (priorite md la plus haute)', () => {
    const m = buildManifestFromTree(
      [
        { path: 'guides/scrum.md' },
        { path: 'guides/scrum.pdf' },
        { path: 'guides/scrum.tex' },
      ],
      { projectName: 'test' },
    )
    expect(m.chapters.filter((c) => c.path.includes('scrum'))).toHaveLength(1)
    const ch = m.chapters.find((c) => c.path === 'guides/scrum.md')
    expect(ch.kind).toBe('markdown')
    expect(ch.companionPdf).toBe('guides/scrum.pdf')
    // Le .tex n'est PAS expose comme compagnon dans cette config (md > pdf
    // > tex). Si l'auteur veut le voir, il peut l'editer dans cursus.yaml.
    expect(ch.companionTex).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('PDF n\'est plus liste comme resource (promu en chapitre)', () => {
    const m = buildManifestFromTree(
      [{ path: 'README.md' }, { path: 'guide.pdf' }],
      { projectName: 'test' },
    )
    // .pdf est devenu chapitre, donc absent de resources
    const pdfResources = (m.resources || []).filter((r) => r.path === 'guide.pdf')
    expect(pdfResources).toHaveLength(0)
    const pdfChapter = m.chapters.find((c) => c.path === 'guide.pdf')
    expect(pdfChapter).toBeDefined()
    expect(pdfChapter.kind).toBe('pdf')
  })

  it('cas reel CESI Mathematiques : 3 paires tex+pdf dans sujets/', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'sujets/qcm-equadiff-integrales.pdf' },
        { path: 'sujets/qcm-equadiff-integrales.tex' },
        { path: 'sujets/qcm-fonctions.pdf' },
        { path: 'sujets/qcm-fonctions.tex' },
        { path: 'sujets/qcm-unique.pdf' },
        { path: 'sujets/qcm-unique.tex' },
        { path: 'corriges/corrige-equadiff-integrales.pdf' },
        { path: 'corriges/corrige-equadiff-integrales.tex' },
      ],
      { projectName: '0-Mathematiques' },
    )
    // README + 3 paires sujets + 1 paire corriges = 5 chapitres
    expect(m.chapters).toHaveLength(5)
    // Tous les sujets sont kind=pdf avec companionTex
    const sujets = m.chapters.filter((c) => c.path.startsWith('sujets/'))
    expect(sujets).toHaveLength(3)
    sujets.forEach((c) => {
      expect(c.kind).toBe('pdf')
      expect(c.companionTex).toBeDefined()
      expect(c.companionTex).toMatch(/\.tex$/)
    })
    validateAgainstSchema(m)
  })

  it('schema accepte chapter avec kind explicite et compagnons', () => {
    const manifest = {
      project: 'Test',
      chapters: [
        { title: 'Guide Scrum', path: 'guides/scrum.md', kind: 'markdown', companionPdf: 'guides/scrum.pdf' },
        { title: 'QCM Equadiff', path: 'sujets/qcm-equadiff.pdf', kind: 'pdf', companionTex: 'sujets/qcm-equadiff.tex' },
      ],
    }
    const r = manifestSchema.safeParse(manifest)
    expect(r.success).toBe(true)
    expect(r.data.chapters[0].kind).toBe('markdown')
    expect(r.data.chapters[0].companionPdf).toBe('guides/scrum.pdf')
    expect(r.data.chapters[1].kind).toBe('pdf')
    expect(r.data.chapters[1].companionTex).toBe('sujets/qcm-equadiff.tex')
  })

  it('schema rejette kind invalide', () => {
    const manifest = {
      project: 'Test',
      chapters: [
        { title: 'A', path: 'a.md', kind: 'invalid_kind' },
      ],
    }
    const r = manifestSchema.safeParse(manifest)
    expect(r.success).toBe(false)
  })
})

// ── v2.74 : prefixe commun detecte -> strippe du titre ─────────────────

describe('buildManifestFromTree : prefixe commun detecte (v2.74)', () => {
  it('sujets avec tous les fichiers qcm-* -> titres sans qcm-', () => {
    const m = buildManifestFromTree(
      [
        { path: 'sujets/qcm-equadiff-integrales.pdf' },
        { path: 'sujets/qcm-fonctions-plusieurs-variables.pdf' },
        { path: 'sujets/qcm-unique.pdf' },
      ],
      { projectName: '0-Mathematiques' },
    )
    const titles = m.chapters.filter((c) => c.path.startsWith('sujets/')).map((c) => c.title)
    expect(titles).toEqual([
      'Equadiff integrales',
      'Fonctions plusieurs variables',
      'Unique',
    ])
  })

  it('corriges avec tous les fichiers corrige-* -> titres sans corrige-', () => {
    const m = buildManifestFromTree(
      [
        { path: 'corriges/corrige-equadiff-integrales.pdf' },
        { path: 'corriges/corrige-unique.pdf' },
      ],
      { projectName: '0-Mathematiques' },
    )
    const titles = m.chapters.filter((c) => c.path.startsWith('corriges/')).map((c) => c.title)
    expect(titles).toEqual(['Equadiff integrales', 'Unique'])
  })

  it('fiches-revision avec tous les fichiers fiche-revision-* -> titres sans fiche-revision-', () => {
    const m = buildManifestFromTree(
      [
        { path: 'fiches-revision/fiche-revision-equadiff.pdf' },
        { path: 'fiches-revision/fiche-revision-integrales.pdf' },
      ],
      { projectName: '0-Mathematiques' },
    )
    const titles = m.chapters.filter((c) => c.path.startsWith('fiches-revision/')).map((c) => c.title)
    expect(titles).toEqual(['Equadiff', 'Integrales'])
  })

  it('dossier avec prefixe mixte -> pas de strip', () => {
    const m = buildManifestFromTree(
      [
        { path: 'divers/qcm-un.pdf' },
        { path: 'divers/exercice-deux.pdf' },
      ],
      { projectName: 'test' },
    )
    const titles = m.chapters.filter((c) => c.path.startsWith('divers/')).map((c) => c.title)
    // Aucun prefixe commun -> titres humanises classiques
    expect(titles).toContain('Qcm un')
    expect(titles).toContain('Exercice deux')
  })

  it('un seul fichier dans un dossier -> pas de detection prefixe (ambigu)', () => {
    const m = buildManifestFromTree(
      [
        { path: 'solo/qcm-unique.pdf' },
      ],
      { projectName: 'test' },
    )
    const chapter = m.chapters.find((c) => c.path === 'solo/qcm-unique.pdf')
    expect(chapter.title).toBe('Qcm unique')
  })

  it('sections avec alias pedagogiques normalisees', () => {
    const m = buildManifestFromTree(
      [
        { path: 'sujets/qcm-a.pdf' },
        { path: 'corriges/corrige-a.pdf' },
        { path: 'fiches-revision/fiche-revision-a.pdf' },
      ],
      { projectName: '0-Mathematiques' },
    )
    const sections = new Set(m.chapters.map((c) => c.section))
    expect(sections.has('Sujets')).toBe(true)
    expect(sections.has('Corriges')).toBe(true)
    expect(sections.has('Fiches de revision')).toBe(true)
  })
})

// ── Normalisation des sections de groupes etudiants v2.66 ────────────────

describe('humanizeDirPath : alias sections groupes etudiants', () => {
  it('LIVRABLES (uppercase) -> Livrables', () => {
    expect(humanizeDirPath('LIVRABLES')).toBe('Livrables')
  })
  it('Livrables (capitalized) -> Livrables', () => {
    expect(humanizeDirPath('Livrables')).toBe('Livrables')
  })
  it('PROSIT singulier -> Prosits (pluriel canonique)', () => {
    expect(humanizeDirPath('PROSIT')).toBe('Prosits')
  })
  it('Prosits (deja canonique) -> Prosits', () => {
    expect(humanizeDirPath('Prosits')).toBe('Prosits')
  })
  it('rendu / rendus -> Rendus', () => {
    expect(humanizeDirPath('rendu')).toBe('Rendus')
    expect(humanizeDirPath('rendus')).toBe('Rendus')
  })
  it('TD / TP / CM -> labels canoniques', () => {
    expect(humanizeDirPath('TD')).toBe('TD')
    expect(humanizeDirPath('TP')).toBe('TP')
    expect(humanizeDirPath('CM')).toBe('Cours magistraux')
  })
  it('dossier non aliase -> humanise classique', () => {
    expect(humanizeDirPath('mon-dossier')).toBe('Mon dossier')
    // Le humanizer n'uppercase que la 1ere lettre, donc php -> Php
    expect(humanizeDirPath('guides/php')).toBe('Guides · Php')
  })
  it('LIVRABLES dans une arborescence imbriquee -> normalise', () => {
    // Le segment LIVRABLES est normalise individuellement dans la chaine
    expect(humanizeDirPath('LIVRABLES/projet1')).toBe('Livrables · Projet1')
  })
})

describe('buildManifestFromTree : sections groupes normalisees', () => {
  it('repo de groupe avec LIVRABLES + PROSIT -> sections Livrables + Prosits', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'LIVRABLES/01-rapport.md' },
        { path: 'PROSIT/p1-mvc.md' },
        { path: 'PROSIT/p2-poo.md' },
      ],
      { projectName: 'SE-groupe-01' },
    )
    const sections = new Set(m.chapters.map((c) => c.section))
    expect(sections.has('Livrables')).toBe(true)
    expect(sections.has('Prosits')).toBe(true)
    // Pas de fuite avec la casse d'origine
    expect(sections.has('LIVRABLES')).toBe(false)
    expect(sections.has('PROSIT')).toBe(false)
  })

  it('repo de groupe avec mix Livrables + LIVRABLES -> meme section unifiee', () => {
    const m = buildManifestFromTree(
      [
        { path: 'Livrables/projet-1.md' },
        { path: 'LIVRABLES/projet-2.md' },
      ],
      { projectName: 'POO-groupe-01' },
    )
    const sections = new Set(m.chapters.map((c) => c.section))
    expect(sections).toEqual(new Set(['Livrables']))
  })
})
