/**
 * Liste d'emojis avec shortcodes style Slack/GitHub pour l'autocomplete ":name".
 *
 * Format : { emoji, shortcode (clé unique), keywords (recherche floue) }.
 * Environ 300 entrees — couverture large des emojis courants sans bundler
 * une lib externe (emoji-mart = ~300 KB, excessif pour ce besoin).
 */

export interface EmojiShortcode {
  emoji: string
  shortcode: string
  keywords?: string[]
}

export const EMOJI_SHORTCODES: EmojiShortcode[] = [
  // ── Smileys ────────────────────────────────────────────────────────────────
  { emoji: '😀', shortcode: 'grinning', keywords: ['smile', 'happy'] },
  { emoji: '😃', shortcode: 'smiley', keywords: ['happy', 'joy'] },
  { emoji: '😄', shortcode: 'smile', keywords: ['happy', 'joy'] },
  { emoji: '😁', shortcode: 'grin', keywords: ['smile'] },
  { emoji: '😆', shortcode: 'laughing', keywords: ['lol', 'satisfied'] },
  { emoji: '😅', shortcode: 'sweat_smile', keywords: ['hot', 'nervous'] },
  { emoji: '🤣', shortcode: 'rofl', keywords: ['rolling', 'laugh'] },
  { emoji: '😂', shortcode: 'joy', keywords: ['cry', 'tears', 'lol'] },
  { emoji: '🙂', shortcode: 'slightly_smiling_face', keywords: ['slight'] },
  { emoji: '🙃', shortcode: 'upside_down_face', keywords: ['flipped'] },
  { emoji: '😉', shortcode: 'wink' },
  { emoji: '😊', shortcode: 'blush', keywords: ['shy'] },
  { emoji: '😇', shortcode: 'innocent', keywords: ['angel', 'halo'] },
  { emoji: '🥰', shortcode: 'smiling_face_with_hearts', keywords: ['love'] },
  { emoji: '😍', shortcode: 'heart_eyes', keywords: ['love'] },
  { emoji: '🤩', shortcode: 'star_struck', keywords: ['star', 'eyes'] },
  { emoji: '😘', shortcode: 'kissing_heart', keywords: ['kiss'] },
  { emoji: '😗', shortcode: 'kissing' },
  { emoji: '😚', shortcode: 'kissing_closed_eyes' },
  { emoji: '😙', shortcode: 'kissing_smiling_eyes' },
  { emoji: '🥲', shortcode: 'smiling_face_with_tear' },
  { emoji: '😋', shortcode: 'yum', keywords: ['tongue'] },
  { emoji: '😛', shortcode: 'stuck_out_tongue' },
  { emoji: '😜', shortcode: 'stuck_out_tongue_winking_eye' },
  { emoji: '🤪', shortcode: 'zany_face', keywords: ['crazy'] },
  { emoji: '😝', shortcode: 'stuck_out_tongue_closed_eyes' },
  { emoji: '🤑', shortcode: 'money_mouth_face' },
  { emoji: '🤗', shortcode: 'hugs' },
  { emoji: '🤭', shortcode: 'hand_over_mouth' },
  { emoji: '🤫', shortcode: 'shushing_face', keywords: ['silence', 'quiet'] },
  { emoji: '🤔', shortcode: 'thinking', keywords: ['hmm'] },
  { emoji: '🫡', shortcode: 'saluting_face' },
  { emoji: '🫠', shortcode: 'melting_face' },
  { emoji: '🤐', shortcode: 'zipper_mouth_face' },
  { emoji: '🤨', shortcode: 'raised_eyebrow' },
  { emoji: '😐', shortcode: 'neutral_face' },
  { emoji: '😑', shortcode: 'expressionless' },
  { emoji: '😶', shortcode: 'no_mouth' },
  { emoji: '😏', shortcode: 'smirk' },
  { emoji: '😒', shortcode: 'unamused' },
  { emoji: '🙄', shortcode: 'roll_eyes' },
  { emoji: '😬', shortcode: 'grimacing' },
  { emoji: '🤥', shortcode: 'lying_face' },
  { emoji: '😌', shortcode: 'relieved' },
  { emoji: '😔', shortcode: 'pensive' },
  { emoji: '😪', shortcode: 'sleepy' },
  { emoji: '🤤', shortcode: 'drooling_face' },
  { emoji: '😴', shortcode: 'sleeping', keywords: ['zzz'] },
  { emoji: '😷', shortcode: 'mask', keywords: ['sick'] },
  { emoji: '🤒', shortcode: 'face_with_thermometer', keywords: ['sick'] },
  { emoji: '🤕', shortcode: 'face_with_head_bandage' },
  { emoji: '🤢', shortcode: 'nauseated_face' },
  { emoji: '🤮', shortcode: 'vomiting_face' },
  { emoji: '🤧', shortcode: 'sneezing_face' },
  { emoji: '🥵', shortcode: 'hot_face' },
  { emoji: '🥶', shortcode: 'cold_face' },
  { emoji: '🥴', shortcode: 'woozy_face' },
  { emoji: '😵', shortcode: 'dizzy_face' },
  { emoji: '🤯', shortcode: 'exploding_head', keywords: ['mind', 'blown'] },
  { emoji: '🤠', shortcode: 'cowboy_hat_face' },
  { emoji: '🥳', shortcode: 'partying_face', keywords: ['party'] },
  { emoji: '🥸', shortcode: 'disguised_face' },
  { emoji: '😎', shortcode: 'sunglasses', keywords: ['cool'] },
  { emoji: '🤓', shortcode: 'nerd_face' },
  { emoji: '🧐', shortcode: 'monocle_face' },
  { emoji: '😕', shortcode: 'confused' },
  { emoji: '😟', shortcode: 'worried' },
  { emoji: '🙁', shortcode: 'slightly_frowning_face' },
  { emoji: '☹️', shortcode: 'frowning_face' },
  { emoji: '😮', shortcode: 'open_mouth' },
  { emoji: '😯', shortcode: 'hushed' },
  { emoji: '😲', shortcode: 'astonished' },
  { emoji: '😳', shortcode: 'flushed' },
  { emoji: '🥺', shortcode: 'pleading_face' },
  { emoji: '😦', shortcode: 'frowning' },
  { emoji: '😧', shortcode: 'anguished' },
  { emoji: '😨', shortcode: 'fearful' },
  { emoji: '😰', shortcode: 'cold_sweat' },
  { emoji: '😥', shortcode: 'disappointed_relieved' },
  { emoji: '😢', shortcode: 'cry' },
  { emoji: '😭', shortcode: 'sob' },
  { emoji: '😱', shortcode: 'scream' },
  { emoji: '😖', shortcode: 'confounded' },
  { emoji: '😣', shortcode: 'persevere' },
  { emoji: '😞', shortcode: 'disappointed' },
  { emoji: '😓', shortcode: 'sweat' },
  { emoji: '😩', shortcode: 'weary' },
  { emoji: '😫', shortcode: 'tired_face' },
  { emoji: '🥱', shortcode: 'yawning_face' },
  { emoji: '😤', shortcode: 'triumph' },
  { emoji: '😡', shortcode: 'rage', keywords: ['angry'] },
  { emoji: '😠', shortcode: 'angry' },
  { emoji: '🤬', shortcode: 'cursing_face' },
  { emoji: '😈', shortcode: 'smiling_imp' },
  { emoji: '👿', shortcode: 'imp' },
  { emoji: '💀', shortcode: 'skull' },
  { emoji: '👻', shortcode: 'ghost' },
  { emoji: '👽', shortcode: 'alien' },
  { emoji: '🤖', shortcode: 'robot' },
  { emoji: '💩', shortcode: 'poop' },
  { emoji: '🤡', shortcode: 'clown_face' },

  // ── Gestures ───────────────────────────────────────────────────────────────
  { emoji: '👋', shortcode: 'wave' },
  { emoji: '🤚', shortcode: 'raised_back_of_hand' },
  { emoji: '🖐️', shortcode: 'raised_hand_with_fingers_splayed' },
  { emoji: '✋', shortcode: 'hand', keywords: ['stop'] },
  { emoji: '🖖', shortcode: 'vulcan_salute' },
  { emoji: '👌', shortcode: 'ok_hand' },
  { emoji: '🤌', shortcode: 'pinched_fingers' },
  { emoji: '🤏', shortcode: 'pinching_hand' },
  { emoji: '✌️', shortcode: 'v', keywords: ['peace'] },
  { emoji: '🤞', shortcode: 'crossed_fingers' },
  { emoji: '🤟', shortcode: 'love_you_gesture' },
  { emoji: '🤘', shortcode: 'the_horns', keywords: ['rock'] },
  { emoji: '🤙', shortcode: 'call_me_hand' },
  { emoji: '👈', shortcode: 'point_left' },
  { emoji: '👉', shortcode: 'point_right' },
  { emoji: '👆', shortcode: 'point_up_2' },
  { emoji: '👇', shortcode: 'point_down' },
  { emoji: '☝️', shortcode: 'point_up' },
  { emoji: '👍', shortcode: 'thumbsup', keywords: ['yes', 'like', '+1'] },
  { emoji: '👎', shortcode: 'thumbsdown', keywords: ['no', 'dislike', '-1'] },
  { emoji: '✊', shortcode: 'fist', keywords: ['power'] },
  { emoji: '👊', shortcode: 'facepunch' },
  { emoji: '🤛', shortcode: 'left_facing_fist' },
  { emoji: '🤜', shortcode: 'right_facing_fist' },
  { emoji: '👏', shortcode: 'clap' },
  { emoji: '🙌', shortcode: 'raised_hands' },
  { emoji: '🫶', shortcode: 'heart_hands' },
  { emoji: '👐', shortcode: 'open_hands' },
  { emoji: '🤲', shortcode: 'palms_up_together' },
  { emoji: '🤝', shortcode: 'handshake' },
  { emoji: '🙏', shortcode: 'pray', keywords: ['thanks'] },
  { emoji: '✍️', shortcode: 'writing_hand' },
  { emoji: '💪', shortcode: 'muscle' },

  // ── Personnes / metiers ────────────────────────────────────────────────────
  { emoji: '👤', shortcode: 'bust_in_silhouette' },
  { emoji: '👥', shortcode: 'busts_in_silhouette' },
  { emoji: '🧑‍💻', shortcode: 'technologist', keywords: ['dev', 'coder'] },
  { emoji: '👨‍🏫', shortcode: 'man_teacher' },
  { emoji: '👩‍🏫', shortcode: 'woman_teacher' },
  { emoji: '👩‍🎓', shortcode: 'woman_student' },
  { emoji: '👨‍🎓', shortcode: 'man_student' },
  { emoji: '🧑‍🎓', shortcode: 'student' },
  { emoji: '🦸', shortcode: 'superhero' },
  { emoji: '🧙', shortcode: 'mage', keywords: ['wizard'] },
  { emoji: '🤷', shortcode: 'shrug' },
  { emoji: '🙋', shortcode: 'raising_hand' },
  { emoji: '🙅', shortcode: 'no_good' },
  { emoji: '🙆', shortcode: 'ok_woman' },
  { emoji: '🤦', shortcode: 'facepalm' },

  // ── Coeurs / amour ─────────────────────────────────────────────────────────
  { emoji: '❤️', shortcode: 'heart' },
  { emoji: '🧡', shortcode: 'orange_heart' },
  { emoji: '💛', shortcode: 'yellow_heart' },
  { emoji: '💚', shortcode: 'green_heart' },
  { emoji: '💙', shortcode: 'blue_heart' },
  { emoji: '💜', shortcode: 'purple_heart' },
  { emoji: '🖤', shortcode: 'black_heart' },
  { emoji: '🤍', shortcode: 'white_heart' },
  { emoji: '🤎', shortcode: 'brown_heart' },
  { emoji: '💔', shortcode: 'broken_heart' },
  { emoji: '❣️', shortcode: 'heart_exclamation' },
  { emoji: '💕', shortcode: 'two_hearts' },
  { emoji: '💞', shortcode: 'revolving_hearts' },
  { emoji: '💓', shortcode: 'heartbeat' },
  { emoji: '💗', shortcode: 'heartpulse' },
  { emoji: '💖', shortcode: 'sparkling_heart' },
  { emoji: '💘', shortcode: 'cupid' },
  { emoji: '💝', shortcode: 'gift_heart' },

  // ── Nature / meteo ────────────────────────────────────────────────────────
  { emoji: '🌱', shortcode: 'seedling' },
  { emoji: '🌿', shortcode: 'herb' },
  { emoji: '🍀', shortcode: 'four_leaf_clover', keywords: ['luck'] },
  { emoji: '🌵', shortcode: 'cactus' },
  { emoji: '🌴', shortcode: 'palm_tree' },
  { emoji: '🌲', shortcode: 'evergreen_tree' },
  { emoji: '🌳', shortcode: 'deciduous_tree' },
  { emoji: '🍃', shortcode: 'leaves' },
  { emoji: '🍂', shortcode: 'fallen_leaf' },
  { emoji: '🍁', shortcode: 'maple_leaf' },
  { emoji: '🌸', shortcode: 'cherry_blossom' },
  { emoji: '🌼', shortcode: 'blossom' },
  { emoji: '🌻', shortcode: 'sunflower' },
  { emoji: '🌺', shortcode: 'hibiscus' },
  { emoji: '🌹', shortcode: 'rose' },
  { emoji: '🌷', shortcode: 'tulip' },
  { emoji: '🌞', shortcode: 'sun_with_face' },
  { emoji: '⭐', shortcode: 'star' },
  { emoji: '🌟', shortcode: 'star2' },
  { emoji: '✨', shortcode: 'sparkles' },
  { emoji: '☀️', shortcode: 'sunny' },
  { emoji: '⛅', shortcode: 'partly_sunny' },
  { emoji: '☁️', shortcode: 'cloud' },
  { emoji: '🌧️', shortcode: 'cloud_with_rain' },
  { emoji: '⛈️', shortcode: 'thunder_cloud_and_rain' },
  { emoji: '❄️', shortcode: 'snowflake' },
  { emoji: '☃️', shortcode: 'snowman' },
  { emoji: '🌈', shortcode: 'rainbow' },
  { emoji: '🔥', shortcode: 'fire' },
  { emoji: '💧', shortcode: 'droplet' },
  { emoji: '🌊', shortcode: 'ocean' },

  // ── Animaux ────────────────────────────────────────────────────────────────
  { emoji: '🐶', shortcode: 'dog' },
  { emoji: '🐱', shortcode: 'cat' },
  { emoji: '🦊', shortcode: 'fox_face' },
  { emoji: '🐻', shortcode: 'bear' },
  { emoji: '🐼', shortcode: 'panda_face' },
  { emoji: '🐨', shortcode: 'koala' },
  { emoji: '🦁', shortcode: 'lion_face' },
  { emoji: '🐯', shortcode: 'tiger' },
  { emoji: '🦄', shortcode: 'unicorn_face' },
  { emoji: '🐸', shortcode: 'frog' },
  { emoji: '🐵', shortcode: 'monkey_face' },
  { emoji: '🙈', shortcode: 'see_no_evil' },
  { emoji: '🙉', shortcode: 'hear_no_evil' },
  { emoji: '🙊', shortcode: 'speak_no_evil' },
  { emoji: '🦉', shortcode: 'owl' },
  { emoji: '🦆', shortcode: 'duck' },
  { emoji: '🐧', shortcode: 'penguin' },
  { emoji: '🐦', shortcode: 'bird' },
  { emoji: '🦋', shortcode: 'butterfly' },
  { emoji: '🐝', shortcode: 'bee' },
  { emoji: '🐙', shortcode: 'octopus' },
  { emoji: '🐬', shortcode: 'dolphin' },

  // ── Nourriture ─────────────────────────────────────────────────────────────
  { emoji: '🍎', shortcode: 'apple' },
  { emoji: '🍐', shortcode: 'pear' },
  { emoji: '🍊', shortcode: 'orange' },
  { emoji: '🍋', shortcode: 'lemon' },
  { emoji: '🍌', shortcode: 'banana' },
  { emoji: '🍉', shortcode: 'watermelon' },
  { emoji: '🍇', shortcode: 'grapes' },
  { emoji: '🍓', shortcode: 'strawberry' },
  { emoji: '🍒', shortcode: 'cherries' },
  { emoji: '🥑', shortcode: 'avocado' },
  { emoji: '🍅', shortcode: 'tomato' },
  { emoji: '🌽', shortcode: 'corn' },
  { emoji: '🥕', shortcode: 'carrot' },
  { emoji: '🍞', shortcode: 'bread' },
  { emoji: '🧀', shortcode: 'cheese' },
  { emoji: '🍔', shortcode: 'hamburger' },
  { emoji: '🍟', shortcode: 'fries' },
  { emoji: '🍕', shortcode: 'pizza' },
  { emoji: '🌭', shortcode: 'hotdog' },
  { emoji: '🌮', shortcode: 'taco' },
  { emoji: '🍣', shortcode: 'sushi' },
  { emoji: '🍩', shortcode: 'doughnut' },
  { emoji: '🍪', shortcode: 'cookie' },
  { emoji: '🎂', shortcode: 'birthday' },
  { emoji: '🍰', shortcode: 'cake' },
  { emoji: '🧁', shortcode: 'cupcake' },
  { emoji: '🍫', shortcode: 'chocolate_bar' },
  { emoji: '🍬', shortcode: 'candy' },
  { emoji: '🍭', shortcode: 'lollipop' },
  { emoji: '☕', shortcode: 'coffee' },
  { emoji: '🍵', shortcode: 'tea' },
  { emoji: '🍺', shortcode: 'beer' },
  { emoji: '🍷', shortcode: 'wine_glass' },
  { emoji: '🥂', shortcode: 'clinking_glasses' },

  // ── Objets / dev ──────────────────────────────────────────────────────────
  { emoji: '💡', shortcode: 'bulb', keywords: ['idea'] },
  { emoji: '🔦', shortcode: 'flashlight' },
  { emoji: '💎', shortcode: 'gem' },
  { emoji: '🔮', shortcode: 'crystal_ball' },
  { emoji: '📚', shortcode: 'books' },
  { emoji: '📖', shortcode: 'book' },
  { emoji: '📝', shortcode: 'memo', keywords: ['note'] },
  { emoji: '✏️', shortcode: 'pencil2' },
  { emoji: '🖊️', shortcode: 'pen' },
  { emoji: '🎨', shortcode: 'art' },
  { emoji: '📌', shortcode: 'pushpin' },
  { emoji: '📎', shortcode: 'paperclip' },
  { emoji: '🗂️', shortcode: 'card_index_dividers' },
  { emoji: '📁', shortcode: 'file_folder' },
  { emoji: '📅', shortcode: 'date', keywords: ['calendar'] },
  { emoji: '📆', shortcode: 'calendar' },
  { emoji: '⏰', shortcode: 'alarm_clock' },
  { emoji: '⏱️', shortcode: 'stopwatch' },
  { emoji: '⏳', shortcode: 'hourglass_flowing_sand' },
  { emoji: '🔔', shortcode: 'bell' },
  { emoji: '🔕', shortcode: 'no_bell' },
  { emoji: '💻', shortcode: 'computer', keywords: ['laptop'] },
  { emoji: '🖥️', shortcode: 'desktop_computer' },
  { emoji: '⌨️', shortcode: 'keyboard' },
  { emoji: '🖱️', shortcode: 'computer_mouse' },
  { emoji: '📱', shortcode: 'iphone', keywords: ['phone'] },
  { emoji: '🎧', shortcode: 'headphones' },
  { emoji: '🎙️', shortcode: 'studio_microphone' },
  { emoji: '🎵', shortcode: 'musical_note' },
  { emoji: '💬', shortcode: 'speech_balloon' },
  { emoji: '💭', shortcode: 'thought_balloon' },
  { emoji: '🔗', shortcode: 'link' },
  { emoji: '⚙️', shortcode: 'gear', keywords: ['settings'] },
  { emoji: '🔧', shortcode: 'wrench' },
  { emoji: '🔨', shortcode: 'hammer' },
  { emoji: '🛠️', shortcode: 'hammer_and_wrench' },
  { emoji: '🎯', shortcode: 'dart', keywords: ['target'] },
  { emoji: '🏆', shortcode: 'trophy' },
  { emoji: '🏅', shortcode: 'medal_sports' },
  { emoji: '🥇', shortcode: 'first_place_medal' },
  { emoji: '🥈', shortcode: 'second_place_medal' },
  { emoji: '🥉', shortcode: 'third_place_medal' },
  { emoji: '🎓', shortcode: 'mortar_board', keywords: ['graduation'] },
  { emoji: '📊', shortcode: 'bar_chart' },
  { emoji: '📈', shortcode: 'chart_with_upwards_trend' },
  { emoji: '📉', shortcode: 'chart_with_downwards_trend' },
  { emoji: '💰', shortcode: 'moneybag' },

  // ── Symboles / statut ─────────────────────────────────────────────────────
  { emoji: '✅', shortcode: 'white_check_mark', keywords: ['check', 'ok'] },
  { emoji: '☑️', shortcode: 'ballot_box_with_check' },
  { emoji: '✔️', shortcode: 'heavy_check_mark' },
  { emoji: '❌', shortcode: 'x', keywords: ['cross', 'no'] },
  { emoji: '❎', shortcode: 'negative_squared_cross_mark' },
  { emoji: '⚠️', shortcode: 'warning' },
  { emoji: '❓', shortcode: 'question' },
  { emoji: '❗', shortcode: 'exclamation' },
  { emoji: '💯', shortcode: '100', keywords: ['hundred'] },
  { emoji: '⚡', shortcode: 'zap', keywords: ['fast', 'lightning'] },
  { emoji: '💥', shortcode: 'boom' },
  { emoji: '💫', shortcode: 'dizzy' },
  { emoji: '🎉', shortcode: 'tada', keywords: ['party', 'celebrate'] },
  { emoji: '🎊', shortcode: 'confetti_ball' },
  { emoji: '🎈', shortcode: 'balloon' },
  { emoji: '🎁', shortcode: 'gift' },
  { emoji: '🏁', shortcode: 'checkered_flag' },
  { emoji: '🚩', shortcode: 'triangular_flag_on_post' },
  { emoji: '🔴', shortcode: 'red_circle' },
  { emoji: '🟠', shortcode: 'orange_circle' },
  { emoji: '🟡', shortcode: 'yellow_circle' },
  { emoji: '🟢', shortcode: 'green_circle' },
  { emoji: '🔵', shortcode: 'blue_circle' },
  { emoji: '🟣', shortcode: 'purple_circle' },
  { emoji: '⚫', shortcode: 'black_circle' },
  { emoji: '⚪', shortcode: 'white_circle' },
  { emoji: '🔺', shortcode: 'small_red_triangle' },
  { emoji: '🔻', shortcode: 'small_red_triangle_down' },
  { emoji: '➕', shortcode: 'heavy_plus_sign' },
  { emoji: '➖', shortcode: 'heavy_minus_sign' },
  { emoji: '➗', shortcode: 'heavy_division_sign' },
  { emoji: '♾️', shortcode: 'infinity' },
  { emoji: '♻️', shortcode: 'recycle' },
  { emoji: '🆕', shortcode: 'new' },
  { emoji: '🆗', shortcode: 'ok' },
  { emoji: '🆘', shortcode: 'sos' },
]

/** Table de lookup rapide par shortcode exact (O(1)). */
export const EMOJI_BY_SHORTCODE: Map<string, string> = new Map(
  EMOJI_SHORTCODES.map(e => [e.shortcode, e.emoji]),
)

/**
 * Cherche les emojis dont le shortcode commence par `query`, puis ceux
 * dont le shortcode contient `query`, puis ceux dont un keyword matche.
 * Maximum 10 resultats. Insensible a la casse.
 */
export function searchEmojiShortcodes(query: string): EmojiShortcode[] {
  const q = query.trim().toLowerCase()
  if (!q) return EMOJI_SHORTCODES.slice(0, 10)

  const startsWith: EmojiShortcode[] = []
  const contains:   EmojiShortcode[] = []
  const keywords:   EmojiShortcode[] = []

  for (const e of EMOJI_SHORTCODES) {
    if (e.shortcode.startsWith(q)) { startsWith.push(e); continue }
    if (e.shortcode.includes(q))   { contains.push(e); continue }
    if (e.keywords?.some(k => k.startsWith(q) || k.includes(q))) keywords.push(e)
  }
  return [...startsWith, ...contains, ...keywords].slice(0, 10)
}
