/**
 * Parsing et validation du fichier `cursus.yaml` racine d'un repo de cours.
 *
 * Le manifest est la source de verite pour Lumen : c'est lui qui decide
 * quels fichiers .md composent le cours, leur ordre, leur titre et leurs
 * metadonnees. Si le manifest est absent, l'auto-manifest (v2.44, cf.
 * lumenAutoManifest.js) prend le relais et genere une version synthetique
 * depuis l'arborescence du repo. Si le yaml est present mais invalide,
 * le repo s'affiche avec un message d'erreur lisible dans l'UI.
 *
 * Format attendu (cursus.yaml) :
 *
 *   project: "Projet 01 — Python pour debutants"     # required
 *   module: "Fondamentaux Python"                     # optional
 *   author: "Rohan Fosse"                             # optional
 *   summary: "Cours d'introduction ..."               # optional
 *   cursusProject: "API Meteo"                        # optional, lien projet Cursus
 *   chapters:                                         # required, min 1
 *     - title: "Introduction"
 *       path: "cours/01-intro.md"
 *       duration: 30                                  # optional, en minutes
 *       summary: "..."                                # optional
 *       prerequis: ["01-intro"]                       # optional
 *       section: "Fondamentaux"                       # optional, regroupement sidebar (v2.44)
 *   resources:                                        # optional
 *     - path: "ressources/cheatsheet.pdf"
 *       kind: "pdf"
 *       title: "Cheatsheet PDF"
 *
 * Champs ajoutes par l'auto-manifest (lecture seulement, pas a ecrire en yaml) :
 *   autoGenerated: true                               # marqueur "manifest synthetique"
 *   truncated: true                                   # repo > 100k entrees GitHub
 */
const YAML = require('js-yaml')
const { z } = require('zod')

const MANIFEST_FILENAME = 'cursus.yaml'

/**
 * Categories de repo Lumen (v2.63). Determine le bucket dans le sommaire
 * et l'icone affichee. Inferable depuis le nom du repo si non explicite.
 */
const KIND_VALUES = ['course', 'prosit', 'workshop', 'miniproject', 'project', 'readme', 'group']

const chapterSchema = z.object({
  title: z.string().min(1).max(200),
  path: z.string().min(1).max(500).regex(/\.md$/i, 'path doit pointer vers un .md'),
  duration: z.number().int().positive().max(600).optional(),
  summary: z.string().max(500).optional(),
  prerequis: z.array(z.string()).optional(),
  // Section affichee dans la sidebar pour grouper les chapitres. Optionnel
  // dans un cursus.yaml ecrit a la main ; toujours renseigne quand le
  // manifest est auto-genere par lumenAutoManifest a partir de l'arborescence.
  section: z.string().max(200).optional(),
}).strict()

const resourceSchema = z.object({
  path: z.string().min(1).max(500),
  kind: z.string().max(50).optional(),
  title: z.string().max(200).optional(),
}).strict()

const manifestSchema = z.object({
  project: z.string().min(1).max(200),
  module: z.string().max(200).optional(),
  author: z.string().max(200).optional(),
  summary: z.string().max(1000).optional(),
  /**
   * Nom du projet Cursus auquel ce cours est rattache. Resolu au sync
   * contre `projects.name` dans la promo du repo (matching case-insensitive
   * + trim + Unicode NFD pour les accents). Si present et match, le lien
   * apparait dans l'onglet Cours du projet et dans le chip LumenChapterViewer.
   */
  cursusProject: z.string().max(200).optional(),
  chapters: z.array(chapterSchema).min(1).max(200),
  resources: z.array(resourceSchema).max(200).optional(),
  // true quand le manifest a ete genere automatiquement depuis l'arborescence
  // du repo (pas de cursus.yaml ecrit a la main). Utilise par l'UI pour
  // afficher un badge "auto" et inviter le prof a personnaliser.
  autoGenerated: z.boolean().optional(),
  // true quand l'arbre source de l'auto-manifest a ete tronque par GitHub
  // (>100k entrees). Le manifest est incomplet — sync surface un warning.
  truncated: z.boolean().optional(),
  // Categorisation v2.63 : determine le bucket dans le sommaire (Cours,
  // Prosits, Workshops, Mini-projets, Projets, README, Groupes etudiants).
  // Si absent, le serveur infere depuis le nom du repo via inferRepoKind().
  kind: z.enum(KIND_VALUES).optional(),
  // Audience cible : 'promo' (defaut, visible par tous) ou 'group' (rendu
  // d'un groupe etudiant specifique). Combine avec groupName pour identifier.
  audience: z.enum(['promo', 'group']).optional(),
  // Nom du groupe quand audience='group' (ex: "Equipe A").
  groupName: z.string().max(100).optional(),
}).strict()

/**
 * Infere la categorie d'un repo depuis son nom. Heuristique simple basee
 * sur les conventions de nommage CESI. L'auteur peut toujours override
 * en mettant `kind:` explicite dans cursus.yaml.
 *
 * Ordre des regles : du plus specifique au plus generique. Les noms
 * ambigus tombent dans 'course' (defaut prudent — la majorite du contenu
 * pedagogique est du cours).
 *
 * @param {string} repoName  Nom court du repo (sans owner/)
 * @returns {string}         Une des valeurs de KIND_VALUES
 */
function inferRepoKind(repoName) {
  if (typeof repoName !== 'string') return 'course'
  const n = repoName.toLowerCase()
  // README en premier : "promo-readme", ".github", "readme-php"
  if (n === 'readme' || n.startsWith('readme-') || n.endsWith('-readme') || n === '.github') return 'readme'
  // Prosit : "prosit-mvc", "prosits-php", "p1-prosit"
  if (n.includes('prosit')) return 'prosit'
  // Workshop / atelier
  if (n.includes('workshop') || n.includes('atelier')) return 'workshop'
  // Mini-projet : "mini-projet-bdd", "miniproject-1", "mini_projet"
  if (n.includes('mini-projet') || n.includes('miniproject') || n.includes('mini_projet') || n.includes('mini-project')) return 'miniproject'
  // Cours : "cours-php", "course-react", "cm-1"
  if (n.includes('cours') || n.includes('course')) return 'course'
  // Groupe etudiant : "groupe-equipe-a", "team-1", "group-react"
  if (/(?:^|[-_])(?:groupe?|equipe|team)(?:[-_]|$)/i.test(n)) return 'group'
  // Projet (apres groupe car "group-project" doit etre group)
  if (n.includes('projet') || n.includes('project')) return 'project'
  return 'course'
}

/**
 * Parse et valide le contenu YAML du manifest.
 * @param {string} yamlText
 * @returns {{ ok: true, manifest: object } | { ok: false, error: string }}
 */
function parseManifest(yamlText) {
  if (typeof yamlText !== 'string' || !yamlText.trim()) {
    return { ok: false, error: 'Fichier cursus.yaml vide' }
  }
  let raw
  try {
    raw = YAML.load(yamlText)
  } catch (err) {
    return { ok: false, error: `YAML invalide : ${err.message}` }
  }
  const parsed = manifestSchema.safeParse(raw)
  if (!parsed.success) {
    const first = parsed.error.issues[0]
    return { ok: false, error: `Schema invalide : ${first.path.join('.')} — ${first.message}` }
  }
  return { ok: true, manifest: parsed.data }
}

module.exports = { parseManifest, MANIFEST_FILENAME, inferRepoKind, KIND_VALUES }
