/**
 * Schema et validation du manifest Lumen.
 *
 * Le manifest est genere automatiquement par lumenAutoManifest.js depuis
 * l'arbre du repo GitHub. Ce fichier definit le schema Zod de validation
 * et l'inference de categorie (`inferRepoKind`).
 */
const { z } = require('zod')

/**
 * Categories de repo Lumen (v2.63). Determine le bucket dans le sommaire
 * et l'icone affichee. Inferable depuis le nom du repo si non explicite.
 */
const KIND_VALUES = ['course', 'prosit', 'workshop', 'miniproject', 'project', 'readme', 'group', 'student']

// Format de chapitre supporte (v2.64). Detecte depuis l'extension du fichier.
const CHAPTER_KIND_VALUES = ['markdown', 'pdf', 'tex']

const chapterSchema = z.object({
  title: z.string().min(1).max(200),
  // v2.64 : on accepte .md, .pdf et .tex. Le rendu cote viewer branche
  // sur l'extension (ou sur le champ kind explicite).
  path: z.string().min(1).max(500).regex(/\.(md|pdf|tex)$/i, 'path doit pointer vers un .md, .pdf ou .tex'),
  duration: z.number().int().positive().max(600).optional(),
  summary: z.string().max(500).optional(),
  prerequis: z.array(z.string()).optional(),
  // Section affichee dans la sidebar pour grouper les chapitres.
  section: z.string().max(200).optional(),
  // Format du chapitre (v2.64). Si absent, infere depuis l'extension du path.
  kind: z.enum(CHAPTER_KIND_VALUES).optional(),
  // Compagnon PDF (v2.64) : si un .md ou .tex a un .pdf jumeau dans le meme
  // dossier, on stocke ici le chemin du PDF pour un bouton "Telecharger PDF".
  companionPdf: z.string().max(500).optional(),
  // Compagnon TeX (v2.64) : si un .pdf est paire a un .tex jumeau, on stocke
  // ici le chemin de la source pour bouton "Voir le source LaTeX".
  companionTex: z.string().max(500).optional(),
}).strict()

const resourceSchema = z.object({
  path: z.string().min(1).max(500),
  kind: z.string().max(50).optional(),
  title: z.string().max(200).optional(),
}).strict()

const manifestSchema = z.object({
  project: z.string().min(1).max(200),
  module: z.string().max(200).optional(),
  author: z.string().max(200).optional(),
  summary: z.string().max(1000).optional(),
  /**
   * Nom du projet Cursus auquel ce cours est rattache. Resolu au sync
   * contre `projects.name` dans la promo du repo (matching case-insensitive
   * + trim + Unicode NFD pour les accents). Si present et match, le lien
   * apparait dans l'onglet Cours du projet et dans le chip LumenChapterViewer.
   */
  cursusProject: z.string().max(200).optional(),
  chapters: z.array(chapterSchema).min(1).max(200),
  resources: z.array(resourceSchema).max(200).optional(),
  // Toujours true — le manifest est genere automatiquement.
  autoGenerated: z.boolean().optional(),
  // true quand l'arbre source de l'auto-manifest a ete tronque par GitHub
  // (>100k entrees). Le manifest est incomplet — sync surface un warning.
  truncated: z.boolean().optional(),
  // Categorisation v2.63 : determine le bucket dans le sommaire (Cours,
  // Prosits, Workshops, Mini-projets, Projets, README, Groupes etudiants).
  // Si absent, le serveur infere depuis le nom du repo via inferRepoKind().
  kind: z.enum(KIND_VALUES).optional(),
  // Audience cible : 'promo' (defaut, visible par tous) ou 'group' (rendu
  // d'un groupe etudiant specifique). Combine avec groupName pour identifier.
  audience: z.enum(['promo', 'group']).optional(),
  // Nom du groupe quand audience='group' (ex: "Equipe A").
  groupName: z.string().max(100).optional(),
}).strict()

/**
 * Infere la categorie d'un repo depuis son nom. Heuristique simple basee
 * sur les conventions de nommage CESI. L'auteur peut toujours override
 * en editant manuellement la categorie.
 *
 * Ordre des regles : du plus specifique au plus generique. Les noms
 * ambigus tombent dans 'course' (defaut prudent — la majorite du contenu
 * pedagogique est du cours).
 *
 * @param {string} repoName  Nom court du repo (sans owner/)
 * @returns {string}         Une des valeurs de KIND_VALUES
 */
function inferRepoKind(repoName) {
  if (typeof repoName !== 'string') return 'course'
  const original = repoName
  const n = repoName.toLowerCase()
  // README en premier : "promo-readme", ".github", "readme-php"
  if (n === 'readme' || n.startsWith('readme-') || n.endsWith('-readme') || n === '.github') return 'readme'
  // Prosit : "prosit-mvc", "prosits-php", "p1-prosit"
  if (n.includes('prosit')) return 'prosit'
  // Workshop / atelier
  if (n.includes('workshop') || n.includes('atelier')) return 'workshop'
  // Mini-projet : "mini-projet-bdd", "miniproject-1", "mini_projet"
  if (n.includes('mini-projet') || n.includes('miniproject') || n.includes('mini_projet') || n.includes('mini-project')) return 'miniproject'
  // Cours : "cours-php", "course-react", "cm-1"
  if (n.includes('cours') || n.includes('course')) return 'course'
  // Groupe etudiant : "groupe-equipe-a", "team-1", "group-react"
  if (/(?:^|[-_])(?:groupe?|equipe|team)(?:[-_]|$)/i.test(n)) return 'group'
  // Projet (apres groupe car "group-project" doit etre group)
  if (n.includes('projet') || n.includes('project')) return 'project'
  // Etudiant individuel (v2.66) : pattern "Nom-Prenom" — deux mots
  // capitalises separes par un tiret, sans mot-cle pedagogique. On
  // travaille sur la chaine ORIGINALE (pas lowercased) pour detecter la
  // capitalisation. Ex: "Astruc-Sebastien", "Bougette-Jean", "Rohan-Fosse".
  if (/^[A-Z][a-z]+(?:-[A-Z][a-z]+)+$/.test(original)) return 'student'
  return 'course'
}

module.exports = { manifestSchema, inferRepoKind, KIND_VALUES, CHAPTER_KIND_VALUES }
